parameters:
  test_path: ''
  package_path: ''
  package_feed: ''
# Test

jobs: 
   - job: 'restore_job'
     displayName: 'restore_job'
     steps:
     - bash: |
         echo 'Testing ${{ parameters.test_path }}'
         echo 'Building ${{ parameters.package_path }}'
         echo 'Restoring from ${{ parameters.package_feed }}'
       displayName: 'Display: Package Path Info'
     

     - task: DotNetCoreCLI@2
       displayName: 'dotnet restore web application'
       inputs:
         command: restore
         projects: '$(build.sourcesdirectory)/WebApplication1/WebApplication1.sln'
         vstsFeed: '${{ parameters.package_feed }}'
         includeNuGetOrg: true
         
     - task: DotNetCoreCLI@2
       displayName: 'dotnet restore WebApplication3'
       inputs:
         command: restore
         projects: '$(build.sourcesdirectory)/WebApplication3/WebApplication3.sln'
         vstsFeed: '${{ parameters.package_feed }}'
         includeNuGetOrg: true     
     
#     - task: DotNetCoreCLI@2
#       displayName: 'Test: Unit Tests'
#       inputs:
#         command: 'test'
#         projects: '${{ parameters.test_path }}/*.csproj'
#         arguments: '--no-restore'
#         failOnStderr: true 
#     
#     # Pack NuGet packages.
#     - task: DotNetCoreCLI@2
#       displayName: 'Build: Pack'
#       inputs:
#         command: 'pack'
#         configuration: 'release'
#         arguments: '--no-restore'
#         versioningScheme: byEnvVar
#         versionEnvVar: Build.BuildNumber
#         packagesToPack: '${{ parameters.package_path }}/*.csproj'
#
